Assume ~/.vim-plugins/ for vim plugins directory
This will simplify update-vim-plugins. Also make it more robust for new
computers too.

diff --git a/update-vim-plugins b/update-vim-plugins
--- a/update-vim-plugins
+++ b/update-vim-plugins
@@ -1,16 +1,18 @@
 #!/bin/sh
 
-if [ ! -d "$1" ]; then
-    echo "Error: invalid vim plugin path '$1'" >&2
+if [ ! -d "$HOME/.vim-plugins" ]; then
+    echo "error: '$HOME/.vim-plugins' is not a directory" >&2
     exit 1
 fi
+cd "$HOME/.vim-plugins"
 
-cd "$1"
+mkdir -p "$HOME/.vim/autoload"
+mkdir -p "$HOME/.vim/bundle"
 
-cp vim-pathogen/autoload/pathogen.vim "$HOME/.vim/autoload/"
+cp vim-pathogen/autoload/pathogen.vim "$HOME/.vim/autoload"
 
 for plugin in *; do
-    cd "$1$plugin"
+    cd "$HOME/.vim-plugins/$plugin"
 
     git submodule update --init --recursive >/dev/null 2>&1
     git upa >/dev/null 2>&1
@@ -18,7 +20,7 @@ for plugin in *; do
     if [ -z "$(find "$HOME/.vim/bundle" -maxdepth 1 -type d -name \
         "$plugin")" ]; then
 
-        mkdir -p "$HOME/.vim/bundle/$plugin"
+        mkdir "$HOME/.vim/bundle/$plugin"
     else
         if [ -z "$(find "$HOME/.vim/bundle/$plugin" -maxdepth 1 -type d -name \
             "plugin")" ]; then
