Update for putting settings on CSUG machines
 - Add $HOME/bin and $HOME/usr/bin to $PATH, if they are directories
 - Copy relevant dot files to home directory on cycle2 with scp
 - Make update-vim-plugins take the path relative to $HOME as an
   argument so it can be run manually on a CSUG machine as well as here
 - Copy the vim-plugins directory
 - Make update-vim-plugins update pathogen

diff --git a/update-vim-plugins b/update-vim-plugins
--- a/update-vim-plugins
+++ b/update-vim-plugins
@@ -1,9 +1,18 @@
 #!/bin/sh
 
-cd "$HOME/Joel/software/vim-plugins"
+if [ -d "$HOME$1" ]; then
+    vim_plugin_path="$1"
+else
+    echo "Error: invalid vim plugin path '$HOME$1'" >&2
+    exit 1
+fi
+
+cd "$HOME$1"
+
+cp vim-pathogen/autoload/pathogen.vim "$HOME/.vim/autoload/"
 
 for plugin in *; do
-    cd "$HOME/Joel/software/vim-plugins/$plugin"
+    cd "$HOME$1$plugin"
 
     git upa >/dev/null 2>&1
 
